version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"  # Asegura que el puerto coincida con el de server.js

    environment:
      - back_URL=https://backend:8000

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
