version: '3.8'

services:
  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      REACT_APP_API_URL: /api 
    networks:
      - app_network

  backend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-Santiii4.git
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      - MYSQLDB_DATABASE=ecommerce
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=root
      - MYSQLDB_HOST=database
      - PORT=8000
    user: root

  frontend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-Santiii4.git
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - PORT=3000
      - REACT_APP_API_URL=/api

  nginx:
    build:
      context: https://github.com/Santiii4/nginx-RIGA.git
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge








